version: '2'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - "5672:5672"
    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
        command: python3 myscrapy.py

    database:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27018:27018"
        volumes:
          - data-volume:/data/db
volumes:
  data-volume:
