version: '2'
services:
    redis:
      container_name: redis
      image: redis:4.0.1-alpine
      ports:
        - "6379"

    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        links:
            - redis
        depends_on:
            - redis
        command: python3 myscrapy.py
